### ISSUE TITLE
No such file or dorectory

### ISSUE THREAD

**Issue by mok-hue** [ZKAW/wifi-deauther#1]
![image](https://user-images.githubusercontent.com/65488834/105980971-94125880-60a6-11eb-8f8f-a07a188041d4.jpeg)

**Comment by ZKAW** [comment]
Hey, thanks for noticing me!

Can you get me the following informations in order to help me solve this problem:

- Your operating system
- Your Python version
- After what precise action the error occurs?

Thank you and have a great day.
