### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by vaalberith** [ZKAW/wifi-deauther#5]
Greetings! i have Orange Pi Zero with TP-Link t2u plus. Installed dkms driver for it and it works ok in aircrack-ng on its own. But when is start Your script, it shows me this:

```
You selected wlx984827226edc for monitoring, waiting for monitor mode to enable...
Following error happened: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ZKAW** [comment]
> Greetings! i have Orange Pi Zero with TP-Link t2u plus. Installed dkms driver for it and it works ok in aircrack-ng on its own. But when is start Your script, it shows me this:
> 
> ```
> You selected wlx984827226edc for monitoring, waiting for monitor mode to enable...
> Following error happened: expected str, bytes or os.PathLike object, not NoneType
> ```
> 

Hi,

This issue usually occurs when your wireless card does not support monitoring mode. Please make sure it's the case.

Have a nice day!

**Comment by vaalberith** [comment]
Thanks for answer!

It supports. But after enabling monitor mode it does not rename to *_mon. Maybe it is driver-related feature in my situation.

Btw, i made my own version of this tool. You can deauth multiple networks with aireplay using it in time-division style. You can check my repo if interested.

Best wishes!
