### ISSUE TITLE
Thank you and one question

### ISSUE THREAD

**Issue by MiranoVerhoef** [ZKAW/wifi-deauther#6]
First of all thank you for making this!

I have a question, woudl a Rasperry Pi 2 Zero with an ubuntu core work? (and then installing your tool)

**Comment by ZKAW** [comment]
> First of all thank you for making this!
> 
> I have a question, woudl a Rasperry Pi 2 Zero with an ubuntu core work? (and then installing your tool)

Unfortunately it's an hardware problem, but you can still check online if the raspberry pi 2 wifi card supports monitoring mode.
