### ISSUE TITLE
Permission denied: '/sys/class/net/

### ISSUE THREAD

**Issue by Pavis0247** [ZKAW/wifi-deauther#7]
Hey, go you know how to solve this error? Permission denied: '/sys/class/net/

**Comment by ZKAW** [comment]
> Hey, go you know how to solve this error? Permission denied: '/sys/class/net/

Hi, make sure you run the program with sudo.

**Comment by Pavis0247** [comment]
I did, but the issue is still going

**Comment by ZKAW** [comment]
> I did, but the issue is still going

 Which OS are you using?

**Comment by Pavis0247** [comment]
I’m using Termux El 6 abr. 2023, a la(s) 3:52 p. m., ZKAW ***@***.***> escribió:﻿

I did, but the issue is still going
Which OS are you using?

**Comment by ZKAW** [comment]
> I’m using Termux El 6 abr. 2023, a la(s) 3:52 p. m., ZKAW ***@***.***> escribió:﻿
> 
> I did, but the issue is still going
> Which OS are you using?
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

So you're on a phone right ?

**Comment by Pavis0247** [comment]
Yes. On a Samsung Fold 3

**Comment by ZKAW** [comment]
> Yes. On a Samsung Fold 3 

That's the issue, the script only works on Linux (on a computer/laptop)

**Comment by Pavis0247** [comment]
Thank you.
